export {
  type DatatypeIriLiteral,
  type LangStringLiteral,
  type StringLiteral,
  type TextLiteral,
  type Literal,
  datatypeIriLiteral,
  langStringLiteral,
  stringLiteral,
  stringLiteralToDatatypeIriLiteral,
  literalsTermEqual,
  isDatatypeIriLiteral,
  isLangStringLiteral,
  isStringLiteral,
  isTextLiteral,
  isLiteral,
  LANG_STRING_DATATYPE_IRI,
} from './base.js';
export {
  type NumericLiteral,
  numericLiteral,
  numericLiteralDatatypeIri,
  numericLiteralToNumber,
  isNumericLiteral,
} from './numeric.js';
export {
  type FullDateLiteral,
  type TimeLiteral,
  type DateTimeLiteral,
  type TemporalLiteral,
  fullDateLiteral,
  timeLiteral,
  dateTimeLiteral,
  isFullDateLiteral,
  isTimeLiteral,
  isDateTimeLiteral,
  isTemporalLiteral,
  FULL_DATE_DATATYPE_IRI,
  TIME_DATATYPE_IRI,
  DATE_TIME_DATATYPE_IRI,
} from './temporal.js';
